export default {
    SET_USER_NAME: 'SET_USER_NAME',
    SET_USER_PHOTO: 'SET_USER_PHOTO',
    SET_VERSION: 'SET_VERSION',
    SET_COPYWRITE: 'SET_COPYWRITE',
    SET_PRODUCT_ID: 'SET_PRODUCT_ID',
    SET_PRODUCT_NAME: 'SET_PRODUCT_NAME',
    SET_ASIDE: 'SET_ASIDE',
    TOOGLE_ASIDE: 'TOOGLE_ASIDE',
    SET_PRODUCT_EXTENDED_ATTRS: 'SET_PRODUCT_EXTENDED_ATTRS',
    ADD_ACTION_MENU: 'ADD_ACTION_MENU',
    ADD_ACTION_AVATAR: 'ADD_ACTION_AVATAR'
}
